services:
  mysql:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend

  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - URL_SERVICE_USER=http://142.93.14.210:4000
      - URL_SERVICE_DOCTOR=http://142.93.14.210:6000
      - URL_SERVICE_CHAT=http://142.93.14.210:7001
      - URL_SERVICE_RATING=http://142.93.14.210:5001
      - URL_SERVICE_APPOINTMENT=http://142.93.14.210:8000

  service_user:
    container_name: service_user
    build: ./service_user
    ports:
      - "4000:4000"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

  service_chat:
    container_name: service_chat
    build: ./service_chat
    ports:
      - "7001:7001"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

  service_rating:
    container_name: service_rating
    build: ./service_rating
    ports:
      - "5001:5001"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

  service_appointment:
    container_name: service_appointment
    build: ./service_appointment
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

  service_doctor:
    container_name: service_doctor
    build: ./service_doctor
    ports:
      - "6000:6000"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

  konsul_dok_service:
    container_name: konsul_dok_service
    build: ../Doctor-Appointment-Api
    ports:
      - "9000:9000"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - backend
    environment:
      - DB_NAME=meet_doctor
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DATABASE_URL=mysql://root:password@db/meet_doctor

networks:
  backend:
    driver: bridge
